#!/bin/bash
# Script para guiar la recuperación desde Browser DevTools

echo "=========================================="
echo "GUÍA PARA RECUPERAR CÓDIGO DESDE BROWSER"
echo "=========================================="
echo ""
echo "PASO 1: Abre el deploy en tu navegador"
echo "   URL: https://7324963f.clases-bot.pages.dev"
echo ""
echo "PASO 2: Abre DevTools (F12)"
echo ""
echo "PASO 3: Ve a la pestaña 'Sources'"
echo ""
echo "PASO 4: Navega a estos archivos:"
echo "   - _next/static/chunks/app/cancelaciones/page.js"
echo "   - _next/static/chunks/app/calendario/page.js"
echo "   - _next/static/chunks/components_Navbar*.js"
echo ""
echo "PASO 5: Para cada archivo:"
echo "   a) Click derecho > 'Save as...'"
echo "   b) O selecciona todo (Cmd+A) y copia (Cmd+C)"
echo "   c) Guarda en: recover-deploy-complete/"
echo ""
echo "PASO 6: Si el código está minificado:"
echo "   - Ve a: https://beautifier.io/"
echo "   - Pega el código"
echo "   - Click 'Beautify'"
echo "   - Copia el resultado"
echo ""
echo "PASO 7: Compara con el código recreado en:"
echo "   - app/cancelaciones/page.tsx"
echo "   - app/calendario/page.tsx"
echo "   - components/Navbar.tsx"
echo ""
echo "=========================================="

